name: stroke
channels:
- anaconda
dependencies:
- python=3.6.7
- pandas=0.25.3
- matplotlib=2.2.2
- scipy=1.3.1
- numpy=1.17.0
- seaborn=0.8.1
- scikit-learn=0.22
- luigi=2.7.5
- tqdm=4.32.1
- jupyterlab=1.0.2
- ipywidgets=7.5.1
- pip
- pip:
  - imbalanced-learn==0.4.3
  - dython==0.3.1